// Autogenerated by hob
window.cls || (window.cls = {});
cls.Scope || (cls.Scope = {});
cls.Scope["1.1"] || (cls.Scope["1.1"] = {});

cls.Scope["1.1"].ServiceResult = function(arr)
{
  this.name = arr[0];
};

