window.ui_strings || ( window.ui_strings  = {} ) 

/* Perspectives */
ui_strings.M_VIEW_LABEL_COMPOSITE_DOM = "DOM"
ui_strings.M_VIEW_LABEL_COMPOSITE_ERROR_CONSOLE = "Error Console"
ui_strings.M_VIEW_LABEL_COMPOSITE_EXPORTS = "Exportieren"
ui_strings.M_VIEW_LABEL_COMPOSITE_SCRIPTS = "Scripts"

ui_strings.M_SETTING_LABEL_GENERAL = "Allgemein"


/* Views */
ui_strings.M_VIEW_LABEL_CALLSTACK = "Call Stack"
ui_strings.M_VIEW_LABEL_COMMAND_LINE = "Command Line"
ui_strings.M_VIEW_LABEL_COMPUTED_STYLE = "Computed Style"
ui_strings.M_VIEW_LABEL_CONSOLE = "Konsole"
ui_strings.M_VIEW_LABEL_DOCUMENTS = "Documente"
ui_strings.M_VIEW_LABEL_DOM = "DOM"
ui_strings.M_VIEW_LABEL_DOM_ATTR = "Eigenschaften"
ui_strings.M_VIEW_LABEL_ENVIRONMENT = "Laufzeitumgebung"
ui_strings.M_VIEW_LABEL_ERROR_ALL = "Alle"
ui_strings.M_VIEW_LABEL_ERROR_BITTORRENT = "Bittorrent"
ui_strings.M_VIEW_LABEL_ERROR_CSS = "CSS"
ui_strings.M_VIEW_LABEL_ERROR_DRAGONFLY = "Dragonfly"
ui_strings.M_VIEW_LABEL_ERROR_HTML = "HTML"
ui_strings.M_VIEW_LABEL_ERROR_JAVA = "Java"
ui_strings.M_VIEW_LABEL_ERROR_M2 = "Mail"
ui_strings.M_VIEW_LABEL_ERROR_NETWORK = "Netzwerk"
ui_strings.M_VIEW_LABEL_ERROR_SCRIPT = "JavaScript"
ui_strings.M_VIEW_LABEL_ERROR_SVG = "SVG"
ui_strings.M_VIEW_LABEL_ERROR_VOICE = "Sprache"
ui_strings.M_VIEW_LABEL_ERROR_WIDGET = "Widget"
ui_strings.M_VIEW_LABEL_ERROR_XML = "XML"
ui_strings.M_VIEW_LABEL_ERROR_XSLT = "XSLT"
ui_strings.M_VIEW_LABEL_EXPORT = "Export"
ui_strings.M_VIEW_LABEL_FRAME_INSPECTION = "Inspektion"
ui_strings.M_VIEW_LABEL_LAYOUT = "Layout"
ui_strings.M_VIEW_LABEL_OBJECT_INSPECTION = "Object Inspektion"
ui_strings.M_VIEW_LABEL_SCRIPTS = "Scripts"
ui_strings.M_VIEW_LABEL_SOURCE = "Quellcode"
ui_strings.M_VIEW_LABEL_STYLES = "Styles"
ui_strings.M_VIEW_LABEL_STYLES = "Styles"
ui_strings.M_VIEW_LABEL_STYLESHEET = "Stylesheet"
ui_strings.M_VIEW_LABEL_STYLESHEETS = "Stylesheets"
ui_strings.M_VIEW_LABEL_THREAD_LOG = "Thread Log"
ui_strings.M_VIEW_SUB_LABEL_METRICS ="Metrik"
ui_strings.M_VIEW_SUB_LABEL_OFFSET_VALUES = "Einbettungswerte"
ui_strings.M_VIEW_SUB_LABEL_PARENT_OFFSETS = "Einbettungshierarchie"

/* Buttons */
ui_strings.S_BUTTON_LABEL_AT_ABORT = "Bei Abort automatisch stoppen"
ui_strings.S_BUTTON_LABEL_AT_ERROR = "Bei Error Script automatisch stoppen"
ui_strings.S_BUTTON_LABEL_AT_EXCEPTION = "Bei Exception automatisch stoppen"
ui_strings.S_BUTTON_LABEL_CLEAR_LOG = "Thread Log löschen"
ui_strings.S_BUTTON_LABEL_CLOSE_WINDOW = "Fenster schliessen"
ui_strings.S_BUTTON_LABEL_CONTINUE = "Continue (F8)"
ui_strings.S_BUTTON_LABEL_EXPORT_DOM = "Aktuelle Sicht des DOMs exportieren"
ui_strings.S_BUTTON_LABEL_EXPORT_LOG = "Thread Log exportieren"
ui_strings.S_BUTTON_LABEL_GET_THE_WOHLE_TREE = "DOM Baum expandieren"
ui_strings.S_BUTTON_LABEL_HELP = "Hilfe"
ui_strings.S_BUTTON_LABEL_HIDEFAULT_PROPS_IN_GLOBAL_SCOPE = "Hide default properties in global scope"
ui_strings.S_BUTTON_LABEL_HIDE_DEFAULT_PROPS_IN_GLOBAL_SCOPE = "Urprungswerte im Global Scope nicht anzeigen"
ui_strings.S_BUTTON_LABEL_LOG_THREADS = "Threads loggen"
ui_strings.S_BUTTON_LABEL_RELOAD_HOST = "Ausgewähltes Browserfenster neu laden"
ui_strings.S_BUTTON_LABEL_SELECT_WINDOW = "Bitte Fenster für Debugging auswählen"
ui_strings.S_BUTTON_LABEL_SETTINGS = "Einstellungen"
ui_strings.S_BUTTON_LABEL_STEP_INTO = "Step Into (F11)"
ui_strings.S_BUTTON_LABEL_STEP_OUT = "Step Out (Shift F11)"
ui_strings.S_BUTTON_LABEL_STEP_OVER = "Step Over (F10)"
ui_strings.S_BUTTON_LABEL_STOP_AT_THREAD = "Bei neuem Script automatisch stoppen"
ui_strings.S_BUTTON_TEXT_APPLY = "Ausführen"

/* Info Text */
ui_strings.S_INFO_DOCUMNENT_LOADING = "Das Dokument wird geladen ..."
ui_strings.S_INFO_NO_RUNTIME_SELECTED = "Bitte Runtime auswählen"
ui_strings.S_INFO_RELOAD_FOR_SCRIPT = "Bitte obenstehendes Reload klicken um alles Scripts für das gewählte Fenster zu laden"
ui_strings.S_INFO_RUNTIME_HAS_NO_SCRIPTS = "Das Dokument enthält keine Scripts"
ui_strings.S_INFO_SERVICE_NOT_AVAILABLE = "Der Service ist nicht verfügbar: %s"
ui_strings.S_INFO_WAITING_FOR_CONNECTION = "Auf einkommende Verbindungen wird gewartet"
ui_strings.S_INFO_WRONG_START = "Opera Dragonfly kann so nicht verwendet werden.\n Bitte entweder diese URL hier einfüllen:\n\n   opera:config > Developer Tools > Developer Tools URL\n\n Oder eine Debuggingumgebung mit Proxy Server aufsetzen."
ui_strings.S_INPUT_DEFAULT_TEXT_FILTER = "Schnellfilter"
ui_strings.S_INPUT_DEFAULT_TEXT_SEARCH = "Suche"

/*Labels */
ui_strings.S_LABEL_PORT = "Port"
ui_strings.S_LABEL_STATUS_INDICATOR = "Statusindikator für Debugger und Browser"

/* Drop downs */ 
ui_strings.S_SELECT_WINDOW_EMPTY = "Bitte Kontext auswählen"

/* Switches */
ui_strings.S_SWITCH_ATTACH_WINDOW = "And Hauptfenster docken"
ui_strings.S_SWITCH_CREATE_SHORTHANDS = "Verkürzte Schreibweise für Properties verwenden"
ui_strings.S_SWITCH_DETACH_WINDOW = "In separates Fenster auskoppeln"
ui_strings.S_SWITCH_FIND_ELEMENT_BY_CLICKING = "Elemente durch Klicken auswählen"
ui_strings.S_SWITCH_HIDE_EMPTY_STRINGS = "Leere Strings nicht anzeigen"
ui_strings.S_SWITCH_HIDE_INITIAL_VALUES = "Ursprungswerte nicht anzeigen"
ui_strings.S_SWITCH_HIDE_SHORTHANDS = "Verkürzte Schreibweise nicht anzeigen"
ui_strings.S_SWITCH_HIEMPTY_STRINGS = "Leere Strings und null-Werte nicht anzeigen"
ui_strings.S_SWITCH_HIGHLIGHT_BY_MOUSE_OVER = "Elemente bei Maus-hover hervorheben"
ui_strings.S_SWITCH_HIINITIAL_VALUES = "Defaultwerte in Computed Styles nicht anzeigen"
ui_strings.S_SWITCH_HISHORTHANDS = "Verkürzte Schreibweise in Computed Styles nicht anzeigen"
ui_strings.S_SWITCH_RELOAD_SCRIPTS_AUTOMATICALLY = "Nach Fensterauswahl Ressourcen automatisch neu laden"
ui_strings.S_SWITCH_REMOTE_DEBUG = "Remote Debugging"
ui_strings.S_SWITCH_SHOW_ATTRIBUTES = "Attribute anzeigen"
ui_strings.S_SWITCH_SHOW_COMMENT_NODES = "Kommentar Nodes anzeigen"
ui_strings.S_SWITCH_SHOW_DOM_INTREE_VIEW = "DOM als Baum anzeigen"
ui_strings.S_SWITCH_SHOW_INITIAL_VALUES = "Ursprungswerte anzeigen"
ui_strings.S_SWITCH_SHOW_SHORTHANDS = "Verkürzte Schreibweise anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_ALL = "Tab 'Alle' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_BITTORRENT = "Tab 'Bittorrent' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_CSS = "Tab 'CSS' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_DRAGONFLY = "Tab 'Dragonfly' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_HTML = "Tab 'HTML' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_JAVA = "Tab 'Java' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_M2 = "Tab 'Mail' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_NETWORK = "Tab 'Netzwerk' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_SCRIPT = "Tab 'Script' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_SVG = "Tab 'SVG' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_VOICE = "Tab 'Sprache' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_WIDGET = "Tab 'Widget' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_XML = "Tab 'XML' anzeigen"
ui_strings.S_SWITCH_SHOW_TAB_XSLT = "Tab 'XSLT' anzeigen"
ui_strings.S_SWITCH_SHOW_VIEWS_MENU = "Views Menü anzeigen"
ui_strings.S_SWITCH_SHOW_WHITE_SPACE_NODES = "White-space Nodes anzeigen"
ui_strings.S_SWITCH_UPDATE_DOM_ON_NODE_REMOVE = "DOM automatisch aktualisieren nach Entfernung von Nodes"
ui_strings.S_SWITCH_UPDATE_DOM_ON_NOREMOVE = "DOM automatisch aktualisieren wenn ein Node entfernt wird"
ui_strings.S_SWITCH_UPDATE_GLOBAL_SCOPE = "Den Global Scope automatisch aktualisieren."
ui_strings.S_SWITCH_USE_LOWER_CASE_TAG_NAMES = "Kleingeschriebene Tags verwenden"
ui_strings.S_SWITCH_USE_SHORTHAND_PROPERTIES = "Verkürzte Schreibweise für Eigenschaften verwenden"



/* UI Text */
ui_strings.S_TEXT_CALL_STACK_FRAME_LINE = "%(FUNCTION_NAME)s: eile %(LINE_NUMBER)s (Script ID %(SCRIPT_ID)s)"
ui_strings.S_TEXT_ECMA_SCRIPT_SCRIPT_ID = "Script ID"
ui_strings.S_TEXT_ECMA_SCRIPT_TYPE_INLINE = "Eingebettet"
ui_strings.S_TEXT_ECMA_SCRIPT_TYPE_LINKED = "Verlinkt"
ui_strings.S_TEXT_ECMA_SCRIPT_TYPE_UNKNOWN = "Unbekannt"
ui_strings.S_TEXT_ENVIRONMENT_DRAGONFLY_VERSION = "Opera Dragonfly Version"
ui_strings.S_TEXT_ENVIRONMENT_OPERATING_SYSTEM = "Betriebssystem"
ui_strings.S_TEXT_ENVIRONMENT_PLATFORM = "Plattform"
ui_strings.S_TEXT_ENVIRONMENT_PROTOCOL_VERSION = "Protokollversion"
ui_strings.S_TEXT_ENVIRONMENT_REVISION_NUMBER = "Revisionsnummer"
ui_strings.S_TEXT_ENVIRONMENT_USER_AGENT = "User-Agent"
ui_strings.S_TEXT_STATUS_SEARCH = "Treffer für %(SEARCH_TERM)s: Treffer %(SEARCH_COUNT_INDEX)s von %(SEARCH_COUNT_TOTAL)s";

